apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: web1
    image: nginx:alpine
    ports:
      - containerPort: 80
        protocol: TCP
  - name: web2
    #image: nginx:alpine
    image: nginxinc/nginx-unprivileged

