kind: Pod  
apiVersion: v1  
metadata:
 name: pod-three
 namespace: mynamespace
spec:  
 containers:
   - name: nginx-pod-one  
     image: nginx:alpine
     resources:
       requests:
         #memory: 768Mi
         memory: 512Mi
         cpu: "1"
       limits:
         memory: 1024Mi  
         cpu: "2"

