kind: Pod
apiVersion: v1
metadata:
  name: pod-limits-cpu
spec:
  containers:
  - name: pod-cpu-demo-ctr
    image: vish/stress
    args:
    - -cpus
    #- "1"
    - "2"
    resources:
      limits:   # maximo
        #cpu: "0.5"
        cpu: "1"
        #cpu: "2"
        #cpu: "3"
      requests: # minimo
        #cpu: "0.5"
        cpu: "1"
        #cpu: "3"
