apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-v2-prefix@kubernetescrd
    #  ↑ formato: <namespace>-<middleware-name>@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: hello-world.info
    http:
      paths:
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: web2-svc
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web1-svc
            port:
              number: 8080
