kind: Pod
apiVersion: v1
metadata:
  name: pod-secret-files
spec:
  volumes:
    - name: secret-volume          # Nombre del volumen
      secret:
        secretName: my-secret            # Referencia al Secret
  containers:
  - name: nginx
    image: nginx:alpine
    volumeMounts:
      - name: secret-volume        # Mismo nombre del volumen
        mountPath: /etc/secret     # Directorio donde se montan
        #readOnly: true
