kind: PersistentVolume
apiVersion: v1
metadata:
  name: my-pv
  labels:
    type: local
spec:
  storageClassName: manual
  #storageClassName: microk8s-hostpath
  capacity:
    storage: 100Mi
  accessModes:
    #- ReadWriteOnce # solo por un node
    - ReadWriteMany  # varios nodos a la vez
    #- ReadWriteOncePod # un Pod a la vez
  hostPath:
    path: "/tmp/datapv"
