apiVersion: v1
kind: Secret
metadata:
  name: secret-dockercfg
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
    eyJhdXRocyI6eyJodHRwczovL2V4YW1wbGUvdjEvIjp7ImF1dGgiOiJvcGVuc2VzYW1lIn19fQo=

# kubectl create secret docker-registry secret-tiger-docker \
#   --docker-email=tiger@acme.example \
#   --docker-username=tiger \
#   --docker-password=pass1234 \
#   --docker-server=my-registry.example:5000
