apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: hello-container
    image: alpine:latest
    command: ['/bin/sh']
    args: ['-c', "while true; do echo Hello Tigo; sleep 10; done"]

